module.exports = {
    products : [
        {
            _id:'1',
            name: 'Diamond',
            category: 'Shirts',
            image: "./images/t1.jpg",
            price: 60,
            brand: 'Billabong',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name: 'Mountain',
            category: 'Shirts',
            image: "./images/t2.jpeg",
            price: 60,
            brand: 'Billabong',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'3',
            name: 'Black & White',
            category: 'Shirts',
            image: "./images/t3.jpeg",
            price: 60,
            brand: 'Billabong',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'4',
            name: 'Full Zip Running Shirts',
            category: 'Forrest',
            image: "./images/t4.jpg",
            price: 60,
            brand: 'Billabong',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'5',
            name: 'Surf Company',
            category: 'Shirts',
            image: "./images/t5.jpeg",
            price: 60,
            brand: 'Billabong',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'6',
            name: 'Surf Goods',
            category: 'Shirts',
            image: "./images/t6.webp",
            price: 60,
            brand: 'Billabong',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        }          
    ]
}